[package]
name = "namiska"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "namiska"
path = "src/main.rs"

[dependencies]
dirs = "5"
enigo = "0.1.3"
device_query = "1.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
toml = "0.8"
